apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostvcafeteria-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: ostvcafeteria-backend
          image: ghcr.io/otsv/backend/ostvcafeteria-backend:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 1024Mi
            requests:
              memory: 512Mi
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017:cafeteria
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: development
            - name: JWT_SECRET
              value: ostvcafeteria
            - name: JWT_ACCESS_EXPIRATION
              value: "7"
            - name: JWT_REFRESH_EXPIRATION
              value: "30"
            - name: ACCOUNTS_SEEDER
              value: "true"
            - name: PRODUCTS_SEEDER
              value: "true"
      imagePullSecrets:
        - name: github-pull-secret 
  
