version: '3.4'

services:
  ostvcafeteria:
    image: ostvcafeteria-backend:latest
    environment: 
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=mongodb://mongo:27017:cafeteria
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - ACCOUNTS_SEEDER=${ACCOUNTS_SEEDER}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on: 
      - mongo
  

  mongo:
    image: mongo:4.0
    volumes: 
      - storage/:/data/db
    restart: unless-stopped
    ports:
      - 27017:27017
volumes:
  storage:
