version: '3.4'

services:
  ostvcafeteria:
    image: ostvcafeteria-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
