version: '3.4'

services:
  ostvcafeteria:
    image: ostvcafeteria-backend:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=mongodb://mongo:27017:cafeteria
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    networks:
      - cafe-network

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - storage/:/data/db
    networks:
      - cafe-network

  redis:
    image: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis-storage/:/data
    networks:
      - cafe-network

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    networks:
      - cafe-network

volumes:
  storage:
  redis-storage:

networks:
  cafe-network:
    driver: bridge
